- hosts: aws
  become: yes
  vars:
    hostname: server-production
    environtment: production
    ruby_version: 2.6.6
    rbenv_root: /home/ec2-user/.rbenv
    rbenv_bin: /home/ec2-user/.rbenv/libexec/rbenv
    bundler_version: 2.2.33 
  tasks:
    - debug: msg="hello world"
    - debug: var=ansible_distribution
    - name: yum update
      yum: name=* state=latest
    - name: install basic packages
      yum: 
        name: "{{ item }}"
      with_items:
        - git
        - gcc
        - openssl-devel
        - libyaml-devel
        - readline-devel
        - zlib-devel
        - libffi-devel
    - name: 'Install rbenv'
      git:
        repo: https://github.com/sstephenson/rbenv.git
        dest: /usr/local/rbenv
    - name: 'rbenvのshファイルを配置'
      template:
        src: rbenv_system.sh.j2
        dest: /etc/profile.d/rbenv.sh
        owner: root
        group: root
        mode: 0755
    - name: 'ruby-buildインストール'
      git:
        repo: https://github.com/sstephenson/ruby-build.git
        dest: /usr/local/rbenv/plugins/ruby-build
    - name: 'deploy用のグループを作成'
      group:
        name: deploy
    - name: 'rbenvディレクトリの所有グループをdeployに変更'
      file:
        path: /usr/local/rbenv
        owner: root
        group: deploy
        recurse: yes
        state: directory
    - name: 'rubyインストール'
      shell: bash -lc "rbenv install --skip-existing 2.6.6"
    - name: 'globalセット'
      shell: bash -lc "rbenv global 2.6.6"
    - name: 'bundlerインストール'
      gem:
        name: bundler
        version: "{{bundler_version}}"
        user_install: no
        executable: /usr/local/rbenv/shims/gem